module.exports = {
  getBarboraScraperResults: require('./getBarboraScraperResults'),
  getRimiScraperResults: require('./getRimiScraperResults'),
  getLastMileScraperResults: require('./getLastMileScraperResults'),
  getVynotekaScraperResults: require('./getVynotekaScraperResults'),
  getTopSearches: require('./getTopSearches'),
  addSearch: require('./addSearch'),
  registerUser: require('./registerUser'),
  logInUser: require('./logInUser'),
  createProfileOptions: require('./createProfileOptions'),
  getProfileOptions: require('./getProfileOptions'),
  deleteProfileOption: require('./deleteProfileOption'),
  getUserName: require('./getUserName'),
  addSearch: require('./addSearch'),
};
